# Generated by Django 5.0.1 on 2024-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimages',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='profileimages',
            name='image',
            field=models.ImageField(default='', upload_to='profiles/images'),
            preserve_default=False,
        ),
    ]
